version: '3.9'

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    pull_policy: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/portainer/data:/data
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true
